[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
exportPdf = "OnType"
outputPath = "$root/$dir/$name"

[[language]]
name = "typst"
language-servers = ["tinymist"]
file-types = ["typst", "typ"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
